runtime: python27
api_version: 1
threadsafe: true


# [START handlers]
handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /.*
  script: main.app
# [END handlers]

libraries:
- name: MySQLdb
  version: "latest"


env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    # mysql+pymysql://rohan:rohan@/bardog?unix_socket=/cloudsql/bardog-179718:asia-northeast1:bardog
    # mysql+pymysql://root@/bardog?unix_socket=/cloudsql/bardog-179718:asia-northeast1:bardog

    #    SQLALCHEMY_DATABASE_URI: >-
    #      'mysql://rohan:rohan@localhost/bardog'
    SECRET_KEY: >-
      sdashd2p39ej2039djasldj2039dojlqw
    APP_SETTINGS: >-
      production

# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: bardog-179718:asia-northeast1:bardog
#[END cloudsql_settings]